my:
  greeting: "Hello World from config.server.client custom"
  list:
    values: 
      - One
      - Two
      - Three
      - Four

db:
  connection: "connection-string-here-from-config-server"
  host: 168.136.7.1
  port: 3535
